version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/ww/html/
hooks:
  #ApplicationStop:
  
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root
  
  ApplicationStart:
    - location: scripts/start_app.sh
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      runas: root
