version: 0.2

phases:
  pre_build:
    commands:
      npm i --only=dev
  build:
    commands:
      npm run build
artifacts:
  files:
    - "dist/**/*"
    - "scripts/**/*"
    - "appspec.yml"
  name: cubetimer-web-artifacts