version: 0.2

phases:
  pre_build:
    commands:
      npm i --only=dev
  build:
    commands:
      npm run build
artifacts:
  files:
    - "**/*"
  base-directory: "dist"
  name: cubetimer-web-artifacts